# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos
LABEL description="A test bed for running the metastore with MySQL"

# Install required packages
RUN yum upgrade -y && \
    yum update -y  && \
    yum install -y mariadb-server mariadb mysql-connector-java* java-1.8.0-openjdk-devel sudo hostname wget which

RUN sudo -u mysql mysql_install_db && \
    { sudo -u mysql mysqld_safe & } && \
    sleep 30 && \
    { \
      echo "CREATE DATABASE hive;"; \
      echo "CREATE USER 'hive'@'localhost' IDENTIFIED BY 'hive';"; \
      echo "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'hive'@'localhost';"; \
      echo "GRANT ALL PRIVILEGES ON hive.* TO 'hive'@'localhost';"; \
      echo "FLUSH PRIVILEGES;"; \
    } > /tmp/createuser.sql && \
    sudo mysql < /tmp/createuser.sql

# Get Hadoop
RUN mkdir /usr/hadoop && \
    cd /usr/hadoop &&  \
    wget http://apache.mirrors.tds.net/hadoop/common/hadoop-2.8.1/hadoop-2.8.1.tar.gz &&  \
    tar zxf hadoop-2.8.1.tar.gz

# Create metastore home and add hive user
RUN mkdir -p /usr/hive/metastore && \
    adduser hive --create-home

# Copy in the tarball, Docker auto unpacks it
ADD __REPLACE_ME_WITH_TARBALL_NAME__ /usr/hive/metastore

# Copy in the config file
COPY metastore-site.xml /usr/hive/metastore/__REPLACE_ME_WITH_UNTARRED_NAME__/conf/metastore-site.xml
    
# setup hive user and cp the jdbc driver into place 
RUN { \
      echo "export HADOOP_HOME=/usr/hadoop/hadoop-2.8.1"; \
      echo "export METASTORE_HOME=/usr/hive/metastore/__REPLACE_ME_WITH_UNTARRED_NAME__"; \
      echo "export PATH=$PATH:$HADOOP_HOME/bin:$METASTORE_HOME/bin"; \
      echo "export JAVA_HOME=/usr"; \
    } >> /home/hive/.bash_profile && \
    cp /usr/share/java/mysql-connector-java.jar /usr/hive/metastore/__REPLACE_ME_WITH_UNTARRED_NAME__/lib && \
    chown -R hive /usr/hive

